apiVersion: apps/v1
kind: Deployment
metadata: 
  name: app-deployment 
  namespace: jenkins-demo
  labels: 
    app: java-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: java-app
          image: meenalgarg2610/jenkins-pipeline:latest
          ports:
            - name: http
              containerPort: 8800
              protocol: TCP
          envFrom:
            - configMapRef: 
                name: example-config
            - secretRef:
                name: secret-info
          resources:
            requests:
              memory: "250Mi"
              cpu: "250m"
            limits:
              memory: "500Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: java-app
  namespace: jenkins-demo
spec:
  type: NodePort
  selector:
    app: java-app
  ports:
    - protocol: TCP
      nodePort: 30158
      port: 8800
      targetPort: 8800 
