apiVersion: app/v1
kind: Deployment
metadata: 
  name: app-deployment
  labels: 
    app: java-app
spec:
  replicas: 3
  selector:
    match-lables:
      app: java-app
    template:
      metadata:
        lables:
          app: java-app
        spec:
          containers:
            - name: java-app
              iamge: meenalgarg2610/jenkins-pipeline:latest
              ports:
                - name: http
                  containerPort: 80
                  protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: java-app
spec:
  type: NodePort
  selector:
    app: java-app
  ports:
    - protocol: TCP
      nodePort: 30158
      port: 80
      targetPort: 80 
